name: "Terraform Apply"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (e.g dev/prod ) must match folder name, e.g. terraform/env/dev or terraform/env/prod)"
        required: true
        type: string

      vm_name:
        description: "VM name ( e.g. dev01 / prod01 ) must match tfvars file, e.g. dev01.tfvars / prod01.tfvars"
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # -----------------------------
      # Set Variables validate environment and vm_name
      # -----------------------------
      - name: Set Variables
        id: vars
        run: |
          ENV=$(echo "${{ inputs.environment }}" | tr '[:upper:]' '[:lower:]')
          VM="${{ inputs.vm_name }}"

          if [ "$ENV" != "dev" ] && [ "$ENV" != "prod" ]; then
            echo "::error:: Invalid environment: $ENV"
            exit 1
          fi

          echo "tfvars_file=env/${ENV}/${VM}.tfvars" >> $GITHUB_OUTPUT
          echo "state_key=state/${ENV}/${VM}/terraform.tfstate" >> $GITHUB_OUTPUT

      # -----------------------------
      # Setup Terraform
      # -----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -------------------------------------------------------------------
      # Setup LXD certificates (optional if using password auth, but recommended for security)
      # Provider will automatically pick up certs from ~/.config/lxc/ if they exist, defined in workflow secrets LXD_CLIENT_CERT and LXD_CLIENT_KEY
      # -------------------------------------------------------------------
      - name: Setup LXD Certs
        if: ${{ secrets.LXD_CLIENT_CERT != '' && secrets.LXD_CLIENT_KEY != '' }}
        run: |
          mkdir -p ~/.config/lxc

          printf "%s" "${{ secrets.LXD_CLIENT_CERT }}" > ~/.config/lxc/client.crt
          printf "%s" "${{ secrets.LXD_CLIENT_KEY }}"  > ~/.config/lxc/client.key

          chmod 600 ~/.config/lxc/client.key
          ls -l ~/.config/lxc/client.* || true

      # -----------------------------
      # Init wirh minio backend
      # -----------------------------
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="endpoint=${{ secrets.MINIO_ENDPOINT }}" \
            -backend-config="bucket=terraform-state" \
            -backend-config="key=${{ steps.vars.outputs.state_key }}" \
            -backend-config="region=us-east-1" \
            -backend-config="access_key=${{ secrets.MINIO_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.MINIO_SECRET_KEY }}" \
            -backend-config="skip_credentials_validation=true" \
            -backend-config="skip_metadata_api_check=true" \
            -backend-config="skip_requesting_account_id=true" \
            -backend-config="force_path_style=true"

      # -----------------------------
      # Apply
      # -----------------------------
      - name: Terraform Apply
        env:
          TF_VAR_lxd_address: ${{ secrets.LXD_ADDRESS }}
          TF_VAR_ansible_ssh_public_key: ${{ secrets.ANSIBLE_SSH_PUBLIC_KEY }}
          # TF_VAR_lxd_trust_password: ${{ secrets.LXD_TRUST_PASSWORD }} --- IGNORE if using lxd certificate ---
          TF_VAR_vm_name: ${{ inputs.vm_name }}
          TF_VAR_environment: ${{ inputs.environment }}
        run: |
          terraform apply -auto-approve \
            -var-file="${{ steps.vars.outputs.tfvars_file }}"
